
from __future__ import annotations

from .models import TrainingWeek, TrainingDay


class DailyGenerator:
    """Build 5H — Convert weekly Road To RAID blocks into daily sessions."""

    def generate(self, weeks: list[TrainingWeek]) -> list[TrainingDay]:
        days: list[TrainingDay] = []
        day_counter = 1
        for week in weeks:
            for i, session in enumerate(week.sessions, start=1):
                load = round(week.target_load / max(1, len(week.sessions)), 1)
                days.append(
                    TrainingDay(
                        day=day_counter,
                        week_number=week.week_number,
                        session_type=session,
                        objective=f"{week.phase.value} phase / session {i}",
                        load=load,
                        notes="Generated by Road To RAID Build 5H",
                    )
                )
                day_counter += 1
        return days
